### ISSUE TITLE
Doesn't work with Debian's/Ubuntu's cal

### ISSUE THREAD

**Issue by perlancar** [kaz-utashiro/App-week#1]
Whatever arguments I give 'week', this error message is displayed instead:

    Usage: cal [general options] [-jy] [[month] year]
           cal [general options] [-j] [-m month] [year]
           ncal -C [general options] [-jy] [[month] year]
           ncal -C [general options] [-j] [-m month] [year]
           ncal [general options] [-bhJjpwySM] [-H yyyy-mm-dd] [-s country_code] [[month] year]
           ncal [general options] [-bhJeoSM] [year]
    General options: [-31] [-A months] [-B months] [-d yyyy-mm]
    cal(1) command format error.

**Comment by eserte** [comment]
It seems to work only with older Debians and Ubuntus --- jessie, wheey and Ubuntu 16.04 seem to work.

**Comment by kaz-utashiro** [comment]
Thank you.  I noticed it today.  It seems not all cal command have '-h' option.  So stop to use it and remove /_[\b]/ sequences.

**Comment by eserte** [comment]
I think this is fixed in 0.03 + 0.04.

**Comment by perlancar** [comment]
Thanks @kaz-utashiro . The calendars look beautiful!

**Comment by kaz-utashiro** [comment]
Thank you!
Set GETOPTEX_RGB24 if you are using 24bit-color terminal.
